### PR TITLE
fix(DatePicker): fix display back wrong of date-picker

### PR DESCRIPTION
**Pull request by wjw-gavin**
close: https://github.com/youzan/vant/issues/11644

### CODE REVIEW

**Comment by chenjiahan** [comment]
We need more test cases to cover different scenarios, can we add a new test case for this issue?

**Comment by wjw-gavin** [comment]
> We need more test cases to cover different scenarios, can we add a new test case for this issue?

ok

**Comment by wjw-gavin** [comment]
Since this problem is caused by multiple picker columns and repeated assignments, I added the test case to the Picker.


https://user-images.githubusercontent.com/19986739/224666504-5f2782fe-a774-4710-ba46-e3a45952a53f.mp4

**Review by chenjiahan — APPROVED** [review]

**Comment by chenjiahan** [comment]
👏🏻

**Pull request merged**
