### PR TITLE
docs: add @inottn and @zhousg to core team

### PR DESCRIPTION
**Pull request by chenjiahan**
Thanks @inottn and @zhousg for your contribution to Vant!

I am delighted to invite you to join the vant core team and enjoy the open source ^_^

## Contributions

Contributions of inottn:

- https://github.com/youzan/vant/commits?author=inottn
- https://github.com/youzan/vant/issues?q=commenter:inottn

Contributions of zhousg:

- https://github.com/youzan/vant/commits?author=zhousg
- https://github.com/youzan/vant/issues?q=commenter:zhousg

## Governance

I have referred to the [Node.js Project Governance](https://github.com/nodejs/node/blob/main/GOVERNANCE.md), and in the future, we can create a Vant Project Governance to clarify the standards for the vant core team.

### CODE REVIEW

**Comment by inottn** [comment]
Thanks for the invitation! I'm excited to join the vant core team.

**Comment by chenjiahan** [comment]
> Thanks for the invitation! I'm excited to join the vant core team.

Welcome to join! ❤️❤️❤️

**Comment by zhousg** [comment]
Thank you for the invitation. I am honored to join.

**Comment by chenjiahan** [comment]
> Thank you for the invitation. I am honored to join.

😄😄

**Pull request merged**
