### PR TITLE
feat(Tabs): add rendered event (#5138)

### PR DESCRIPTION
**Pull request by joe223**

### CODE REVIEW

**Comment by joe223** [comment]
Well, you have already resolved this issue https://github.com/youzan/vant/issues/5138. This PR is useless, I will close it.

**Comment by joe223** [comment]
I  found some issues newly.

- `triggerd` should be `triggered`
- `this.parent.$emit('rendered', this.computedName, this.title);` should be called on `$nextTick` when tab is really rendered (not before render) https://github.com/youzan/vant/blob/ac00d78a46327450b3b0cc87475457deeb7ad673/src/tab/index.js#L47-L49 of course, test case should add some code like this (I guess you already knew):
```javascript
  await later();
  expect(onRendered).toHaveBeenCalledWith(0, 'title1')
```

**Comment by chenjiahan** [comment]
@joe223 you are right. Can you make some changes to this PR to fix these issues?

**Comment by joe223** [comment]
OK, I'll finish this weekend @chenjiahan

**Comment by chenjiahan** [comment]
We plan to release v2.3.0 this morning, so I fixed the nextTick issue to ensure the rendered event works as expected.

https://github.com/youzan/vant/pull/5327

**Comment by joe223** [comment]
@chenjiahan Thanks for all your hard work

**Pull request closed without merging**
