### PR TITLE
chore: extend type GlobalComponents in "@vue/runtime-core"

### PR DESCRIPTION
**Pull request by zhousg**
### Before submitting a pull request, please make sure the following is done:

1. Read the [contributing guide](https://github.com/vant-ui/vant/blob/main/.github/CONTRIBUTING.md).
2. If you've added code that should be tested, add tests.
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).

#### Title Format

type(ComponentName?)：commit message

Example：

- docs: fix typo in quickstart
- build: optimize build speed
- fix(Button): incorrect style
- feat(Button): add color prop

Allowed Types:

- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
- breaking change

### CODE REVIEW

**Review by chenjiahan — APPROVED** [review]

**Comment by jiadesen** [comment]
没看懂，用 `pnpm` 的话 `node_modules` 下哪还有 `@vue`

**Comment by zhousg** [comment]
Hello, can you unify, 'vue' or '@vue/runtime-core', and why you depend on @vue/runtime

**Comment by chenjiahan** [comment]
直接中文交流吧，能再详细描述下改动的背景和用意吗？

**Comment by zhousg** [comment]
> 直接中文交流吧，能再详细描述下改动的背景和用意吗？

我关闭吧

**Pull request closed without merging**
