### PR TITLE
fix(Field): label-align top works well with label-width

### PR DESCRIPTION
**Pull request by Jungzl**
related: #11611 #11676

### CODE REVIEW

**Comment by chenjiahan** [comment]
The #11676 is updated, can we compare the two implementations and find a better one?

**Comment by Jungzl** [comment]
Since #11611 introduced a new bug in #11675, I think revert it and consider a better solution is a way to go. `labelAlign = "top"` is a special condition, in fact, this has nothing to do with align itself, because top actually changes the layout of the label and input so I just pass `labelWidth` down to the real label tag to archive the same goal.

**Comment by Jungzl** [comment]
BTW, if #11676 is considered as a better solution for DOM consistency, can I make a new PR about cli part or am I miss something that I just don't know where to update snapshots

**Review by chenjiahan — APPROVED** [review]

**Comment by chenjiahan** [comment]
I will accpet this PR as it works better in more scenarios, thanks for the contribution ^_^

**Pull request merged**
