### PR TITLE
fix(List): scoped style not applied to first child

### PR DESCRIPTION
**Pull request by chenjiahan**
https://github.com/youzan/vant/issues/7121

### CODE REVIEW

**Comment by syb024** [comment]
van-pull-refresh  van-list   问题依然存在,下拉刷新后范围样式失效

**Comment by chenjiahan** [comment]
@syb024 提供下 codesandbox 复现链接

**Comment by syb024** [comment]
image

**Comment by chenjiahan** [comment]
get，下个版本修复

**Pull request merged**
