### PR TITLE
feat(Sticky): 添加吸底

### PR DESCRIPTION
**Pull request by kooriookami**
#7531

### Before submitting a pull request, please make sure the following is done:

1. Read the [contributing guide](https://github.com/youzan/vant/blob/dev/.github/CONTRIBUTING.md).
2. If you've added code that should be tested, add tests.
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).

#### Title Format

type(ComponentName?)：commit message

Example：

- docs: fix typo in quickstart
- build: optimize build speed
- fix(Button): incorrect style
- feat(Button): add color prop

Allowed Types:

- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
- breaking change

### CODE REVIEW

**Comment by chenjiahan** [comment]
单测挂了喔，麻烦先看下

**Comment by kooriookami** [comment]
这个单元测试真是写到崩溃ORZ

**Review by chenjiahan — APPROVED** [review]

**Comment by chenjiahan** [comment]
哈哈~ Sticky 的单测是难写的，辛苦啦，已 merge

**Comment by chenjiahan** [comment]
补充一个疑问：`width: `${state.width}px`,` 设置 width 的目的是什么嘞

**Comment by kooriookami** [comment]
> 补充一个疑问：`width: `${state.width}px`,` 设置 width 的目的是什么嘞

加上width可以让元素在绝对定位时候保持宽度不变，使用`text-align`等样式的正常。

**Comment by chenjiahan** [comment]
了解👌

**Pull request merged**
