### PR TITLE
fix(stylelint): 修复 找不到 stylelint-config bug

### PR DESCRIPTION
**Pull request by dushaobindoudou**
### Before submitting a pull request, please make sure the following is done:

1. Read the [contributing guide](https://github.com/youzan/vant/blob/dev/.github/CONTRIBUTING.md).
2. If you've added code that should be tested, add tests.
3. If you've changed APIs, update the documentation.
4. Ensure the test suite passes (`npm test`).

#### Title Format

type(ComponentName?)：commit message

Example：

- docs: fix typo in quickstart
- build: optimize build speed
- fix(Button): incorrect style
- feat(Button): add color prop

Allowed Types:

- fix
- feat
- docs
- perf
- test
- types
- build
- chore
- refactor
- breaking change

### CODE REVIEW

**Comment by chenjiahan** [comment]
@vant/cli 的依赖中已经包含了 @vant/stylelint-config，无须再次安装呢

https://github.com/youzan/vant/blob/9d96614425392bffa73e8df4feb554413cf52078/packages/vant-cli/package.json#L55

**Comment by dushaobindoudou** [comment]
yarn 安装的时候，好像并没有安装vant的dev依赖，@vant/cli 没有安装，@vant/stylelint-config也没有，

yarn 1.19.1

如果这样的话
@vant/stylelint-config  应该放到依赖里面

**Comment by chenjiahan** [comment]
可以重新 yarn 试下，@vant/cli 是肯定要安装的

**Comment by dushaobindoudou** [comment]
> 可以重新 yarn 试下，@vant/cli 是肯定要安装的

yarn 好像解决不行

为啥 cli是必须的？

**Comment by chenjiahan** [comment]
cli 是构建工具

**Pull request closed without merging**
